rm -f bin/*.o
rm -f bin/*.lst
rm -f bin/*.dbg
rm -f bin/mvscmd
rm -f bin/mvscmdauth
rm -f tests/*.expected
rm -f tests/*.actual
rm -f testsrc/*.cmd
rm -f opttests/*.expected
rm -f opttests/*.actual
rm -f opttestsrc/*.cmd
