 DEFINE CLUSTER (NAME (IBMUSER.MVSCMD.IDCAMS.VSAM) -
 VOLUMES(B2SYS1) CYLINDERS(1 1) -
 RECORDSIZE (72 100) KEYS(9 8) INDEXED)
 REPRO INFILE(DATAIN) OUTDATASET(IBMUSER.MVSCMD.IDCAMS.VSAM) ELIMIT(200)
